name: ludwig-bench
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1j
  - pip=21.0.1
  - python=3.7.10
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.12.0
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - attrs==20.3.0
    - bayesmark==0.0.8
    - blessings==1.7
    - cachetools==4.2.1
    - cffi==1.14.5
    - chardet==4.0.0
    - click==7.1.2
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - colorful==0.5.4
    - configspace==0.4.18
    - cython==0.29.22
    - dill==0.3.3
    - docker==4.4.4
    - elasticsearch==7.11.0
    - et-xmlfile==1.0.1
    - fiber==0.2.1
    - filelock==3.0.12
    - flatbuffers==1.12
    - gast==0.3.3
    - gitdb==4.0.5
    - gitpython==3.1.14
    - google-api-core==1.26.1
    - google-auth==1.27.1
    - google-auth-oauthlib==0.4.3
    - google-pasta==0.2.0
    - googleapis-common-protos==1.53.0
    - gpustat==0.6.0
    - gputil==1.4.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - hiredis==1.1.0
    - idna==2.10
    - importlib-metadata==3.7.2
    - iniconfig==1.1.1
    - joblib==1.0.1
    - jsonschema==3.2.0
    - keras-preprocessing==1.1.2
    - kubernetes==12.0.1
    - git+https://github.com/ludwig-ai/ludwig.git@ed5ae805a6fb28f7ba02a50fffebdd24ab52d436 
    - lxml==4.6.2
    - markdown==3.3.4
    - msgpack==1.0.2
    - multidict==5.1.0
    - nnpy-bundle==1.4.2.post1
    - numexpr==2.7.3
    - numpy==1.19.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencensus==0.7.12
    - opencensus-context==0.1.2
    - openpyxl==3.0.7
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.1.4
    - pathvalidate==2.3.2
    - pluggy==0.13.1
    - poap==0.1.26
    - prometheus-client==0.9.0
    - protobuf==3.15.6
    - psutil==5.8.0
    - py==1.10.0
    - py-spy==0.3.4
    - pyaml==20.4.0
    - pyarrow==3.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pydoe2==1.3.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pysot==0.3.3
    - pytest==6.2.2
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
    - redis==3.5.3
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.24.1
    - scikit-optimize==0.8.1
    - scipy==1.6.1
    - six==1.15.0
    - smmap==3.0.5
    - tables==3.6.1
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.1
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - tfa-nightly==0.12.0.dev20201215223743
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - tqdm==4.59.0
    - typeguard==2.11.1
    - typing-extensions==3.7.4.3
    - urllib3==1.24.3
    - websocket-client==0.58.0
    - werkzeug==1.0.1
    - wget==3.2
    - wrapt==1.12.1
    - xarray==0.17.0
    - xlrd==2.0.1
    - xlwt==1.3.0
    - yarl==1.6.3
    - zipp==3.4.1
prefix: /Users/avanikanarayan/opt/anaconda3/envs/ludwig-bench
